import { defineConfig } from "vite";
import type { Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import path from "path";
import fs from "fs";

const SERVER_ONLY_PACKAGES = [
  "pg",
  "pg-pool",
  "pg-cloudflare",
  "pg-connection-string",
  "postgres-bytea",
  "postgres-date",
  "postgres-interval",
  "jose",
  "resend",
  "node:async_hooks",
  "node:process",
  "node:fs",
  "node:path",
  "node:net",
  "node:tls",
  "node:stream",
  "node:util",
  "node:events",
  "node:buffer",
  "node:dns",
  "node:crypto",
  "async_hooks",
  "@tanstack/start-storage-context",
];

// All named exports from server-side files/packages that get statically imported.
// Rollup needs these declared explicitly — a Proxy alone won't satisfy static analysis.
// Generated by grepping all `export` declarations from *.server.ts and *.service.ts files.
const ALL_SERVER_EXPORTS = `
const noop = () => undefined;
const noopPromise = async () => undefined;
export default new Proxy({}, { get: () => noop });

// jose
export const SignJWT = function() { return { setProtectedHeader: () => ({ sign: noopPromise }) }; };
export const jwtVerify = noopPromise;
export const decodeJwt = noop;

// @tanstack/start-storage-context
export const getStartContext = noop;
export const createStorage = noop;
export const getStorage = noop;
export class AsyncLocalStorage {
  run(_s, fn, ...args) { return fn(...args); }
  getStore() { return undefined; }
}
export const AsyncResource = noop;

// pg
export const Pool = function() {};
export const Client = function() {};

// resend
export const Resend = function() { return { emails: { send: noopPromise } }; };

// node:crypto
export const createHmac = noop;
export const timingSafeEqual = () => false;
export const randomBytes = () => new Uint8Array(0);
export const createHash = noop;

// db/index.server
export const query = noopPromise;
export const queryOne = noopPromise;
export const execute = noopPromise;
export const withTransaction = async (_fn) => undefined;
export const getPool = noop;

// auth.server
export const signAccessToken = noopPromise;
export const signRefreshToken = noopPromise;
export const verifyToken = noopPromise;
export const generateOtp = () => '000000';

// config.server
export const getServerConfig = () => ({});

// resend.server
export const sendOtpEmail = noopPromise;

// blink.server
export const createLightningInvoice = noopPromise;
export const payLightningInvoice = noopPromise;
export const payLightningAddress = noopPromise;
export const payOnChain = noopPromise;
export const getOnChainFee = noopPromise;
export const confirmMockPayment = noopPromise;
export const getLightningInvoiceStatus = noopPromise;
export const getBlinkBalance = noopPromise;
export const getBtcWalletId = noopPromise;

// lipila.server
export const requestPayment = noopPromise;
export const disburseFunds = noopPromise;
export const getLipilaStatus = noopPromise;

// treasury.server
export const getTreasuryBalances = noopPromise;
export const getTreasuryState = noopPromise;
export const convertPartialUsdToBtc = noopPromise;
export const convertUsdToBtcForWithdrawal = noopPromise;
export const getUsdWalletId = noopPromise;
export const initTreasuryState = noopPromise;
export const swapBtcToUsd = noopPromise;
export const swapUsdToBtc = noopPromise;
export const satsToUsdCents = noop;
export const startPriceLoop = noop;

// webhook-handlers.server
export const handleBlinkWebhook = noopPromise;
export const handleLipilaWebhook = noopPromise;

// treasury-api.server
export const handleTreasuryApi = noopPromise;

// protection.service
export const evaluateProtection = noopPromise;

// withdrawal.service
export const prepareWithdrawal = noopPromise;
export const buildWithdrawalMeta = noopPromise;
export const recoverStuckWithdrawals = noopPromise;

// wallet.functions server-side helpers
export const creditWallet = noopPromise;
export const creditVault = noopPromise;
export const lockIntoVault = noopPromise;
export const unlockFromVault = noopPromise;
`;

function renameHtmlPlugin(): Plugin {
  return {
    name: "rename-html",
    closeBundle() {
      const src = "dist/mobile/index.mobile.html";
      const dst = "dist/mobile/index.html";
      if (fs.existsSync(src)) {
        fs.writeFileSync(dst, fs.readFileSync(src, "utf8"));
        fs.unlinkSync(src);
      }
    },
  };
}

function mobileServerShimPlugin(): Plugin {
  return {
    name: "mobile-server-shim",
    enforce: "pre",
    resolveId(id) {
      // Shim all *.server.ts / *.server.js files
      if (/\.server(\.[jt]sx?)?$/.test(id)) {
        return "\0mobile-shim:" + id;
      }
      // Shim known server-only npm packages
      if (SERVER_ONLY_PACKAGES.some((pkg) => id === pkg || id.startsWith(pkg + "/"))) {
        return "\0mobile-shim:" + id;
      }
      return null;
    },
    load(id) {
      if (id.startsWith("\0mobile-shim:")) return ALL_SERVER_EXPORTS;
      return null;
    },
  };
}

export default defineConfig({
  plugins: [
    mobileServerShimPlugin(),
    react(),
    tailwindcss(),
    tsconfigPaths(),
    renameHtmlPlugin(),
  ],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
  build: {
    outDir: "dist/mobile",
    emptyOutDir: true,
    rollupOptions: {
      input: "index.mobile.html",
    },
  },
  define: {
    "process.env.NODE_ENV": JSON.stringify("production"),
  },
});
